#!/usr/bin/env bash

sudo add-apt-repository universe -y
sudo apt update

############
#   libs   #
############

# dev tools
sudo apt install build-essential zlib1g-dev libffi-dev libssl-dev libbz2-dev libreadline-dev libsqlite3-dev liblzma-dev tk-dev

# wireplumber
# TODO: sanity-check if any of this is required for 23.04
sudo apt install wireplumber
sudo apt install libspa-0.2-bluetooth
sudo apt install pipewire-audio-client-libraries
sudo apt install pavucontrol
sudo apt remove pulseaudio-module-bluetooth

# MPEG-4 AAC
sudo apt install ubuntu-restricted-extras

# fonts
sudo apt install fonts-firacode
sudo apt install fonts-inconsolata

############
# runtimes #
############

# java
sudo apt install -y openjdk-17-jdk
java -version

# ruby
sudo apt install rbenv

############
#    cli   #
############

# cli
sudo apt install tree

############
#   apps   #
############

# emacs
sudo apt install emacs -y

# evolution
sudo apt install evolution

# vlc
sudo apt install vlc

# inkscape
sudo apt install inkscape

# spotify
curl -sS https://download.spotify.com/debian/pubkey_7A3A762FAFD4A51F.gpg | sudo gpg --dearmor --yes -o /etc/apt/trusted.gpg.d/spotify.gpg
echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list
sudo apt-get update
sudo apt-get install spotify-client

# flatpak
sudo apt install flatpak
sudo apt install gnome-software-plugin-flatpak

############
# flatpaks #
############

flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

echo "You will need to reboot before the flatpak binaries are on the path."
echo "(Press <enter> to continue.)"
rebooten=""
read rebooten

# apostrophe

flatpak install flathub org.gnome.gitlab.somas.Apostrophe


#########
# snaps #
#########

# bitwarden (deb and flatpak don't support updates)
sudo snap install bitwarden
