#!/usr/bin/env bash

sudo add-apt-repository universe

sudo apt update

# java
sudo apt install -y openjdk-17-jdk
java -version

# ruby
sudo apt install rbenv

# cli
sudo apt  install tree

# fonts
sudo apt install fonts-firacode
sudo apt install fonts-inconsolata

# emacs
sudo apt install emacs -y

